import { Student, EmulationCriterion, ScoreLog, ClassConfig } from '../types';

export const INITIAL_CONFIG: ClassConfig = {
  className: 'Lớp 6A3',
  schoolName: 'Trường THCS Hải Châu I',
  schoolYear: '2025 - 2026',
  currentWeek: 4,
  currentSemester: 1,
  gasUrl: '', // Can be configured by user in Settings
  audioEnabled: true,
  autoConfetti: true,
  baselineScore: 100,
};

export const INITIAL_CRITERIA: EmulationCriterion[] = [
  // Điểm Cộng
  { id: 'TC_P01', name: 'Xung phong phát biểu xây dựng bài', type: 'plus', points: 5, category: 'hoc_tap', icon: '✋' },
  { id: 'TC_P02', name: 'Đạt điểm 9 hoặc 10 (kiểm tra miệng/15p)', type: 'plus', points: 10, category: 'hoc_tap', icon: '⭐' },
  { id: 'TC_P03', name: 'Nhặt được của rơi trả người đánh mất', type: 'plus', points: 10, category: 'ne_nep', icon: '💎' },
  { id: 'TC_P04', name: 'Giúp đỡ bạn bè trong học tập tiến bộ', type: 'plus', points: 5, category: 'hoc_tap', icon: '🤝' },
  { id: 'TC_P05', name: 'Trực nhật lớp sạch sẽ, đúng giờ', type: 'plus', points: 5, category: 've_sinh', icon: '🧹' },
  { id: 'TC_P06', name: 'Hoàn thành xuất sắc nhiệm vụ được giao', type: 'plus', points: 10, category: 'hoat_dong', icon: '🎯' },
  { id: 'TC_P07', name: 'Tham gia tích cực phong trào của trường/đội', type: 'plus', points: 15, category: 'hoat_dong', icon: '🏆' },
  { id: 'TC_P08', name: 'Đeo khăn quàng, đồng phục đúng tác phong cả tuần', type: 'plus', points: 5, category: 'ne_nep', icon: '👔' },

  // Điểm Trừ
  { id: 'TC_M01', name: 'Đi học muộn / vào lớp trễ', type: 'minus', points: 5, category: 'ne_nep', icon: '⏰' },
  { id: 'TC_M02', name: 'Không thuộc bài / chưa làm bài tập về nhà', type: 'minus', points: 10, category: 'hoc_tap', icon: '📖' },
  { id: 'TC_M03', name: 'Mất trật tự, nói chuyện riêng trong giờ học', type: 'minus', points: 5, category: 'ne_nep', icon: '🗣️' },
  { id: 'TC_M04', name: 'Không mặc đúng đồng phục / quên đeo khăn quàng', type: 'minus', points: 5, category: 'ne_nep', icon: '🧣' },
  { id: 'TC_M05', name: 'Sử dụng điện thoại / làm việc riêng không xin phép', type: 'minus', points: 10, category: 'ne_nep', icon: '📱' },
  { id: 'TC_M06', name: 'Ăn quà vặt trong lớp học', type: 'minus', points: 5, category: 've_sinh', icon: '🍿' },
  { id: 'TC_M07', name: 'Vứt rác bừa bãi, không giữ vệ sinh chung', type: 'minus', points: 5, category: 've_sinh', icon: '🗑️' },
  { id: 'TC_M08', name: 'Nói tục, cãi lại cán bộ lớp hoặc gây gổ', type: 'minus', points: 15, category: 'ne_nep', icon: '🚫' },
  { id: 'TC_M09', name: 'Quên trực nhật / trốn trực nhật tổ', type: 'minus', points: 10, category: 've_sinh', icon: '⚠️' },
];

export const INITIAL_STUDENTS: Student[] = [
  // TỔ 1 (10 HS)
  { id: 'HS01', name: 'Nguyễn Gia Bảo', group: 1, gender: 'nam', totalPoints: 125, weeklyPoints: 25, previousRank: 2, roleTitle: 'Lớp trưởng' },
  { id: 'HS02', name: 'Trần Thảo Linh', group: 1, gender: 'nu', totalPoints: 115, weeklyPoints: 15, previousRank: 3, roleTitle: 'Tổ trưởng Tổ 1' },
  { id: 'HS03', name: 'Lê Minh Khang', group: 1, gender: 'nam', totalPoints: 105, weeklyPoints: 5, previousRank: 8, roleTitle: 'Học sinh' },
  { id: 'HS04', name: 'Phạm Quỳnh Anh', group: 1, gender: 'nu', totalPoints: 110, weeklyPoints: 10, previousRank: 5, roleTitle: 'Học sinh' },
  { id: 'HS05', name: 'Hoàng Quốc Việt', group: 1, gender: 'nam', totalPoints: 95, weeklyPoints: -5, previousRank: 14, roleTitle: 'Học sinh' },
  { id: 'HS06', name: 'Vũ Thị Ngọc Hà', group: 1, gender: 'nu', totalPoints: 100, weeklyPoints: 0, previousRank: 12, roleTitle: 'Tổ phó' },
  { id: 'HS07', name: 'Đặng Tuấn Anh', group: 1, gender: 'nam', totalPoints: 85, weeklyPoints: -15, previousRank: 22, roleTitle: 'Học sinh' },
  { id: 'HS08', name: 'Bùi Phương Uyên', group: 1, gender: 'nu', totalPoints: 105, weeklyPoints: 5, previousRank: 9, roleTitle: 'Học sinh' },
  { id: 'HS09', name: 'Ngô Thanh Tùng', group: 1, gender: 'nam', totalPoints: 90, weeklyPoints: -10, previousRank: 20, roleTitle: 'Học sinh' },
  { id: 'HS10', name: 'Đỗ Yến Nhi', group: 1, gender: 'nu', totalPoints: 105, weeklyPoints: 5, previousRank: 10, roleTitle: 'Học sinh' },

  // TỔ 2 (10 HS)
  { id: 'HS11', name: 'Phan Bảo Nam', group: 2, gender: 'nam', totalPoints: 130, weeklyPoints: 30, previousRank: 1, roleTitle: 'Lớp phó học tập' },
  { id: 'HS12', name: 'Dương Mai Phương', group: 2, gender: 'nu', totalPoints: 120, weeklyPoints: 20, previousRank: 4, roleTitle: 'Tổ trưởng Tổ 2' },
  { id: 'HS13', name: 'Hồ Đăng Khoa', group: 2, gender: 'nam', totalPoints: 100, weeklyPoints: 0, previousRank: 13, roleTitle: 'Học sinh' },
  { id: 'HS14', name: 'Trịnh Cẩm Tú', group: 2, gender: 'nu', totalPoints: 110, weeklyPoints: 10, previousRank: 6, roleTitle: 'Học sinh' },
  { id: 'HS15', name: 'Lương Đình Trọng', group: 2, gender: 'nam', totalPoints: 95, weeklyPoints: -5, previousRank: 16, roleTitle: 'Học sinh' },
  { id: 'HS16', name: 'Tạ Minh Trang', group: 2, gender: 'nu', totalPoints: 105, weeklyPoints: 5, previousRank: 11, roleTitle: 'Học sinh' },
  { id: 'HS17', name: 'Đinh Xuân Phúc', group: 2, gender: 'nam', totalPoints: 80, weeklyPoints: -20, previousRank: 31, roleTitle: 'Học sinh' },
  { id: 'HS18', name: 'Cao Khánh Linh', group: 2, gender: 'nu', totalPoints: 105, weeklyPoints: 5, previousRank: 15, roleTitle: 'Học sinh' },
  { id: 'HS19', name: 'Chu Hải Đăng', group: 2, gender: 'nam', totalPoints: 100, weeklyPoints: 0, previousRank: 17, roleTitle: 'Học sinh' },
  { id: 'HS20', name: 'Võ Thục Đoan', group: 2, gender: 'nu', totalPoints: 110, weeklyPoints: 10, previousRank: 7, roleTitle: 'Tổ phó' },

  // TỔ 3 (10 HS)
  { id: 'HS21', name: 'Lê Hoàng Bách', group: 3, gender: 'nam', totalPoints: 115, weeklyPoints: 15, previousRank: 7, roleTitle: 'Tổ trưởng Tổ 3' },
  { id: 'HS22', name: 'Nguyễn Thị Thuỳ Dương', group: 3, gender: 'nu', totalPoints: 105, weeklyPoints: 5, previousRank: 18, roleTitle: 'Đội cờ đỏ' },
  { id: 'HS23', name: 'Trần Quang Vinh', group: 3, gender: 'nam', totalPoints: 90, weeklyPoints: -10, previousRank: 24, roleTitle: 'Học sinh' },
  { id: 'HS24', name: 'Phạm Hồng Nhung', group: 3, gender: 'nu', totalPoints: 100, weeklyPoints: 0, previousRank: 19, roleTitle: 'Học sinh' },
  { id: 'HS25', name: 'Đoàn Nhật Minh', group: 3, gender: 'nam', totalPoints: 110, weeklyPoints: 10, previousRank: 8, roleTitle: 'Học sinh' },
  { id: 'HS26', name: 'Huỳnh Kim Ngân', group: 3, gender: 'nu', totalPoints: 95, weeklyPoints: -5, previousRank: 21, roleTitle: 'Tổ phó' },
  { id: 'HS27', name: 'Tạ Quốc Huy', group: 3, gender: 'nam', totalPoints: 85, weeklyPoints: -15, previousRank: 28, roleTitle: 'Học sinh' },
  { id: 'HS28', name: 'Mai Lan Hương', group: 3, gender: 'nu', totalPoints: 100, weeklyPoints: 0, previousRank: 23, roleTitle: 'Học sinh' },
  { id: 'HS29', name: 'Vũ Đức Thịnh', group: 3, gender: 'nam', totalPoints: 75, weeklyPoints: -25, previousRank: 38, roleTitle: 'Học sinh' },
  { id: 'HS30', name: 'Bùi Ánh Tuyết', group: 3, gender: 'nu', totalPoints: 105, weeklyPoints: 5, previousRank: 25, roleTitle: 'Học sinh' },

  // TỔ 4 (10 HS)
  { id: 'HS31', name: 'Nguyễn Hoàng Long', group: 4, gender: 'nam', totalPoints: 110, weeklyPoints: 10, previousRank: 9, roleTitle: 'Tổ trưởng Tổ 4' },
  { id: 'HS32', name: 'Trần Bảo Ngọc', group: 4, gender: 'nu', totalPoints: 125, weeklyPoints: 25, previousRank: 3, roleTitle: 'Lớp phó văn thể' },
  { id: 'HS33', name: 'Lê Tiến Dũng', group: 4, gender: 'nam', totalPoints: 95, weeklyPoints: -5, previousRank: 26, roleTitle: 'Học sinh' },
  { id: 'HS34', name: 'Hoàng Trúc Mai', group: 4, gender: 'nu', totalPoints: 105, weeklyPoints: 5, previousRank: 27, roleTitle: 'Đội cờ đỏ' },
  { id: 'HS35', name: 'Đặng Minh Triết', group: 4, gender: 'nam', totalPoints: 100, weeklyPoints: 0, previousRank: 29, roleTitle: 'Học sinh' },
  { id: 'HS36', name: 'Vũ Thảo Nguyên', group: 4, gender: 'nu', totalPoints: 100, weeklyPoints: 0, previousRank: 30, roleTitle: 'Tổ phó' },
  { id: 'HS37', name: 'Nguyễn Hữu Tài', group: 4, gender: 'nam', totalPoints: 70, weeklyPoints: -30, previousRank: 40, roleTitle: 'Học sinh' },
  { id: 'HS38', name: 'Phan Diệu Huyền', group: 4, gender: 'nu', totalPoints: 105, weeklyPoints: 5, previousRank: 32, roleTitle: 'Học sinh' },
  { id: 'HS39', name: 'Trịnh Hữu Thắng', group: 4, gender: 'nam', totalPoints: 90, weeklyPoints: -10, previousRank: 35, roleTitle: 'Học sinh' },
  { id: 'HS40', name: 'Lâm Tuệ Mẫn', group: 4, gender: 'nu', totalPoints: 110, weeklyPoints: 10, previousRank: 10, roleTitle: 'Học sinh' },
];

export const INITIAL_LOGS: ScoreLog[] = [
  {
    id: 'LOG_01',
    timestamp: '27/09/2026 07:15',
    scorerName: 'Cô Chu Thị Mai',
    scorerRole: 'Giáo viên chủ nhiệm',
    studentId: 'HS11',
    studentName: 'Phan Bảo Nam',
    studentGroup: 2,
    criterionId: 'TC_P02',
    criterionName: 'Đạt điểm 9 hoặc 10 (kiểm tra miệng/15p)',
    type: 'plus',
    pointsChanged: 10,
    note: 'Đạt 10 điểm kiểm tra miệng môn Toán',
  },
  {
    id: 'LOG_02',
    timestamp: '27/09/2026 07:45',
    scorerName: 'Trần Bảo Ngọc',
    scorerRole: 'Cờ đỏ',
    studentId: 'HS37',
    studentName: 'Nguyễn Hữu Tài',
    studentGroup: 4,
    criterionId: 'TC_M01',
    criterionName: 'Đi học muộn / vào lớp trễ',
    type: 'minus',
    pointsChanged: -5,
    note: 'Đến trường lúc 7h20',
  },
  {
    id: 'LOG_03',
    timestamp: '27/09/2026 08:30',
    scorerName: 'Nguyễn Gia Bảo',
    scorerRole: 'Lớp trưởng',
    studentId: 'HS01',
    studentName: 'Nguyễn Gia Bảo',
    studentGroup: 1,
    criterionId: 'TC_P01',
    criterionName: 'Xung phong phát biểu xây dựng bài',
    type: 'plus',
    pointsChanged: 5,
    note: 'Tiết Ngữ văn sôi nổi',
  },
  {
    id: 'LOG_04',
    timestamp: '27/09/2026 09:10',
    scorerName: 'Hoàng Trúc Mai',
    scorerRole: 'Cờ đỏ',
    studentId: 'HS29',
    studentName: 'Vũ Đức Thịnh',
    studentGroup: 3,
    criterionId: 'TC_M02',
    criterionName: 'Không thuộc bài / chưa làm bài tập về nhà',
    type: 'minus',
    pointsChanged: -10,
    note: 'Chưa soạn bài Lịch Sử',
  },
  {
    id: 'LOG_05',
    timestamp: '27/09/2026 10:05',
    scorerName: 'Cô Chu Thị Mai',
    scorerRole: 'Giáo viên chủ nhiệm',
    studentId: 'HS32',
    studentName: 'Trần Bảo Ngọc',
    studentGroup: 4,
    criterionId: 'TC_P07',
    criterionName: 'Tham gia tích cực phong trào của trường/đội',
    type: 'plus',
    pointsChanged: 15,
    note: 'Đại diện lớp đạt giải Nhất vẽ tranh An toàn giao thông',
  },
];
